version: "3.3"
services:
  terminal:
    container_name: terminal
    restart: unless-stopped
    image: terminal
    env_file:
      - .env
    build: .
    command: serve -s build
    ports:
      - "127.0.0.1:3030:3000"
